Update schema.json
lorawan-schema/draft-devices pull request #7
Opened 2020-11-18 17:43 UTC by laurensslats

Editions, add fields:
- resellerURL
- video link
- email

2020-11-19 09:39 UTC, johanstokking requested changes

2020-11-19 09:39 UTC, johanstokking commented on schema.json
> +        },
```suggestion
        "email": {
          "type": "string",
          "format": "email"
        },
```

2020-11-19 09:39 UTC, johanstokking commented on schema.json
> +      "pattern": "(https?:\/\/)www.(youtube.com\/watch[?]v=([a-zA-Z0-9_-]{11}))|(https?:\/\/)www.(youtu.be\/([a-zA-Z0-9_-]))|https?:\/\/(www.)?vimeo.com\/([0-9]{9})"
Do you have a source for this? The video ID in the mobile YouTube URL seems off; no length check there.

2020-11-19 09:39 UTC, johanstokking commented on schema.json
> +        },
Nice!

2020-11-19 09:40 UTC, johanstokking requested changes

2020-11-19 09:40 UTC, johanstokking commented on schema.json
> +        "resellerURL": {
```suggestion
        "resellerURLs": {
```

2020-11-19 09:41 UTC, johanstokking commented on schema.json
> +        "resellerURL": {
Should we differentiate per region for the resellers?

Also with only URLs, we'll only be able to display a bullet list of URLs. If that's fine, then I'm good with it too.

2020-11-19 15:19 UTC, laurensslats commented on schema.json
> +      "pattern": "(https?:\/\/)www.(youtube.com\/watch[?]v=([a-zA-Z0-9_-]{11}))|(https?:\/\/)www.(youtu.be\/([a-zA-Z0-9_-]))|https?:\/\/(www.)?vimeo.com\/([0-9]{9})"
Updated. 

Played around with this tool: https://www.regextester.com/

It now supports all of these formats.
https://youtu.be/ZZbVsrYPOGE
https://www.youtube.com/watch?v=dsfasdf5623
http://www.youtube.com/watch?v=iwGFalTRHDA
http://www.youtube.com/watch?v=t-ZRX8984sc
http://vimeo.com/620922414
https://www.vimeo.com/462092214

2020-11-19 17:21 UTC, laurensslats commented on schema.json
> +        "resellerURL": {
Yes, good point. Updated

2020-11-23 09:15 UTC, johanstokking requested changes

2020-11-23 09:15 UTC, johanstokking commented on schema.json
> +      "pattern": "^(https?:\/\/www.(youtube.com\/watch[?]v=([a-zA-Z0-9_-]{0,}))|(https?:\/\/)(www.)?(youtu.be\/([a-zA-Z0-9_-]{0,}))|https?:\/\/(www.)?vimeo.com\/([0-9]{0,}))"
```suggestion
      "pattern": "^(?:https?:\\\/\\\/(?:www\\.)?youtu(?:be\\.com\\\/watch\\?v=|\\.be\\\/)(?:[\\w\\-\\_]*)(?:&(amp;)?[\\w\\?=]*)?)$|^(?:https?:\\\/\\\/(?:www\\.)?vimeo\\.com\\\/(?:channels\\\/(?:\\w+\\\/)?|groups\\\/([^\\\/]*)\\\/videos\\\/|)(?:\\d+)(?:|\\\/\\?))$"
```

- More compact form for YouTube
- Allows for various Vimeos formats
- Full length match
- Fully escaped
- No accidental matches with unescaped `.`

2020-11-23 09:15 UTC, johanstokking commented on schema.json
> +                },
Needs to be an array of enum

Let's go with the G20 excluding individual EU members. We can always expand later;

```suggestion
                "regions": {
                    "type": "array",
                    "items": {
                    	"enum": [
                    		"Argentina",
                    		"Australia",
                    		"Brazil",
                    		"Canada",
                    		"China",
                    		"European Union",
                    		"India",
                    		"Indonesia",
                    		"Japan",
                    		"Mexico",
                    		"Russia",
                    		"Saudi Arabia",
                    		"South Africa",
                    		"South Korea",
                    		"Turkey",
                    		"United States",
                    		"Other
                    	]
                    }
                },
```

2020-11-23 09:59 UTC, johanstokking approved these changes

2020-11-23 10:04 UTC, merged